[tool.poetry]
name = "document-merge-service"
version = "4.7.0"
description = "Merge Document Template Service"
authors = ["Adfinis AG"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
Babel = "^2.9.1"
Django = "^3.2.13"
django-cors-headers = "^3.10.0"
django-environ = "^0.8.1"
django-filter = "^21.1"
djangorestframework = "^3.12.4"
docx-mailmerge = "^0.5.0"
docxtpl = "0.14.2"
Jinja2 = "^3.0.3"
jsonpath = "^0.82"
mysqlclient = "2.0.3"
psycopg2-binary = "2.9.1"
python-dateutil = "^2.8.2"
python-memcached = "1.59"
requests = "^2.26.0"
uWSGI = "2.0.20"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
factory-boy = "^3.2.1"
flake8 = "^4.0.1"
flake8-debugger = "^4.0.0"
flake8-docstrings = "^1.6.0"
flake8-isort = "^4.1.1"
flake8-string-format = "^0.3.0"
flake8-tuple = "^0.4.1"
gitlint = "^0.16.0"
isort = "^5.10.0"
pydocstyle = "^6.1.1"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-django = "^4.4.0"
pytest-env = "^0.6.2"
pytest-factoryboy = "< 2.2.0"
pytest-mock = "^3.6.1"
pytest-randomly = "^3.10.1"
requests-mock = "^1.9.3"
python-semantic-release = "^7.19.2"
snapshottest = "^0.6.0"
psutil = "^5.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
